FROM nvidia/cuda:11.8.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

#get deps   
RUN echo "Installing dependencies..."
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip

RUN pip install --upgrade pip

RUN apt-get install -y curl
RUN apt-get install -y git

# YOLO
RUN pip install ultralytics

# DWPose
RUN pip install -U openmim
RUN mim install mmengine
RUN mim install "mmcv>=2.0.1"
RUN mim install "mmpose>=1.1.0"

# YoloNasNet
RUN pip install super-gradients

#RUN apt update
RUN apt-get install -y --no-install-recommends ffmpeg

RUN pip install ffmpeg-python

RUN pip install docker

# Label Box API
RUN pip install "labelbox[data]"

WORKDIR /usr/src/app

ADD "https://api.github.com/repos/Surfytom/Swim2DPose/commits?per_page=1" latest_commit
RUN git clone https://github.com/Surfytom/Swim2DPose

WORKDIR /usr/src/app/Swim2DPose

# Downloads weights for dw pose large model
RUN curl -o Pipeline/DWPoseLib/Models/384x288DWPoseLargeModel.pth -L 'https://drive.usercontent.google.com/download?id=1Oy9O18cYk8Dk776DbxpCPWmJtJCl-OCm&export=download&authuser=0&confirm=yes'

# Downloads Yolo weights from ultralytics
RUN curl -o Pipeline/YoloUltralyticsLib/Models/yolov8x-seg.pt -L 'https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8x-seg.pt'