FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu20.04

RUN DEBIAN_FRONTEND=noninteractive apt update && DEBIAN_FRONTEND=noninteractive apt install -y --allow-change-held-packages \
    ffmpeg \
    python3 \
    python3-pip \
    python3-tk \
    git \
    libgl1 \
    libglib2.0-0\
    libsm6 \
    libxrender1 \
    libxext6

RUN pip3 install torch torchvision torchaudio cython pycocotools gdown ninja matplotlib \
    cython_bbox numpy scipy opencv-python pyyaml tensorboardx terminaltables tqdm visdom \
    iopath fvcore pytorch3d

RUN pip install pip --upgrade

WORKDIR /home

RUN mkdir /build

ADD /HalpeCOCOAPI /build/HalpeCOCOAPI
RUN cd /build/HalpeCOCOAPI/PythonAPI && python3 setup.py build develop --user

ENV CUDA_HOME='/usr/local/cuda'
RUN TORCH_CUDA_ARCH_LIST="6.1;7.5;8.6" \
    PATH=/usr/local/cuda/bin/:$PATH \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH

RUN cd /build && git clone https://github.com/MVIG-SJTU/AlphaPose.git
WORKDIR /build/AlphaPose
RUN mkdir -p detector/yolox/data && \
    gdown 1G_03v91ckIfi2Wwu_uuMMQ4nHBWoklwn -O detector/yolox/data/yolox_x.pth && \
    gdown 10QLwqRk334W86KrFuDFXpEw1kbrXHCSP -O pretrained_models/halpe26_fast_res50_256x192.pth
    gdown 1DsottUmO-UODGi_OH6cm1euvSnxmpG2N -O pretrained_models/fast_res50_256x192.pth

#RUN CC=gcc-9 CXX=g++-9 python3 setup.py build develop --user